### ISSUE TITLE
Refused to display when in "browser device"

### ISSUE THREAD

**Issue by joomlaevolved** [krisrak/jquery-cordova-oauth2#19]
Hi,

when I try to window.open to a _blank  target (as it is in your fine js library), then it gets a 

**"Refused to display  in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'."**

Do you have a clue why this is happening in the browser device and not in Android?

It is a pain to have to recompile to the android device or simulator. 

:-)

**Comment by krisrak** [comment]
This is not for webapp that opens in browser or mobile browser, it is for html5 cordova app only

**Comment by joomlaevolved** [comment]
Yes indeed. The application is a cordova application, but testing is much faster in the "browser device".
Anyway, if I find a solution and share it with you. The problem seems to exist in x-frame header premissions on most servers being SAMEORIGIN.

**Comment by krisrak** [comment]
That SAMEORIGIN error will not occur when opened in Cordova app, cause it is not using a browser window, it will use InAppBrowser which will not be blocked. You cannot test on browser cause it will not use InAppBrowser. If u want to test Cordova app easily without building and installing on device, then try using Intel XDK, push and test with the Intel App Preview app

**Comment by joomlaevolved** [comment]
Thanks Mr Krisral!!! That seems to be really userfull!!

 I wil have a look at Intel XDK.
