### ISSUE TITLE
How can I get extra values from Facebook?

### ISSUE THREAD

**Issue by sebastialonso** [krisrak/jquery-cordova-oauth2#20]
First off, great plugin!

I'm currently receiving just the Facebook token, what about name, email and so on?
I tried playing with the scope object but with no success. Is it possible?

**Comment by krisrak** [comment]
If there is any extra info in oauth response, it will be in the second param of success callback:

```
$.oauth2({
        auth_url: 'https://www.facebook.com/dialog/oauth',
        response_type: 'token',
        client_id: 'CLIENT-ID-FROM-FACEBOOK',
        redirect_uri: 'http://www.yourwebsite.com/redirect',
        other_params: {scope: 'basic_info', display: 'popup'}
    }, function(token, response){
        makeAPICalls(token);
    }, function(error, response){
        alert(error);
    }); 
```
If not use the `access_token` and make the actual API call to get that info

**Comment by sebastialonso** [comment]
Thank you for your quick response!

**Comment by joshuaquek** [comment]
Just going to post this here, for those who need to know how to retrieve a user's info using an access token:

http://stackoverflow.com/questions/3546677/how-to-get-the-facebook-user-id-using-the-access-token
