### ISSUE TITLE
App stays at account.google.com approval page

### ISSUE THREAD

**Issue by sagarinnova** [krisrak/jquery-cordova-oauth2#8]
Hi,
Thank you for the plugin. I am not sure where I am doing wrong. 
I am using cordova version 4.1.2 and building the app for iOS. Below are the steps I followed.

1. Created the client id for iOS application 
2. In index.html copied the client ID and client Secret
3. response_type is given as "code"
4. redirect_uri I have given as "urn:ietf:wg:oauth:2.0:oob" which auto created while creating client ID
5. Have also installed in app browser plugin

Now when I run the app and click on "Oauth2 Login" button, the in app browser is opened with Google login screen. 

I gave the credential and then , google displays the approval page with my application name. 
When I click on "Accept" , I get the page with my login name and display pic , along with the "code". However I am not able to proceed further. The page has message "Please copy this code, switch to your application and paste it there" with a "code" in a textbox. 

It should logically take me to success call back , however it stays on approval page. Attaching the page. 

Please let me know , where am I doing mistake. 

Thanks,
Sagar
![ios simulator screen shot 01-jan-2015 7 44 27 pm](https://cloud.githubusercontent.com/assets/2559305/5592350/02da82c8-91f1-11e4-9075-c4de9811c8e4.png)

**Comment by sagarinnova** [comment]
Issue was with the redirect URL, once I gave the dummy URL , I was able to redirect back to app and received the access_token. 

Thanks.

**Comment by djbagalacsa** [comment]
Hi may i ask where did you create the dummy url to make this work? thanks in advance i hope you can help me too!
